package com.boj.guidance.util;

import java.util.HashMap;
import java.util.Map;

public class AlgorithmVectorUtil {

    public static final Map<String, Integer> vector = new HashMap<>();

    static {
        vector.put("수학", 6110);
        vector.put("구현", 5270);
        vector.put("다이나믹 프로그래밍", 3870);
        vector.put("자료 구조", 3659);
        vector.put("그래프 이론", 3544);
        vector.put("그리디 알고리즘", 2406);
        vector.put("문자열", 2292);
        vector.put("브루트포스 알고리즘", 2094);
        vector.put("그래프 탐색", 1934);
        vector.put("정렬", 1778);
        vector.put("기하학", 1438);
        vector.put("애드 혹", 1388);
        vector.put("정수론", 1380);
        vector.put("트리", 1344);
        vector.put("세그먼트 트리", 1254);
        vector.put("이분 탐색", 1172);
        vector.put("사칙연산", 1080);
        vector.put("시뮬레이션", 1026);
        vector.put("너비 우선 탐색", 949);
        vector.put("해 구성하기", 948);
        vector.put("누적 합", 907);
        vector.put("조합론", 864);
        vector.put("많은 조건 분기", 805);
        vector.put("깊이 우선 탐색", 792);
        vector.put("최단 경로", 741);
        vector.put("비트마스킹", 691);
        vector.put("해시를 사용한 집합과 맵", 597);
        vector.put("데이크스트라", 566);
        vector.put("백트래킹", 507);
        vector.put("트리를 사용한 집합과 맵", 471);
        vector.put("분리 집합", 458);
        vector.put("스위핑", 458);
        vector.put("파싱", 439);
        vector.put("우선순위 큐", 409);
        vector.put("트리에서의 다이나믹 프로그래밍", 407);
        vector.put("분할 정복", 405);
        vector.put("스택", 363);
        vector.put("매개 변수 탐색", 361);
        vector.put("두 포인터", 361);
        vector.put("게임 이론", 344);
        vector.put("최대 유량", 322);
        vector.put("소수 판정", 311);
        vector.put("느리게 갱신되는 세그먼트 트리", 292);
        vector.put("비트필드를 이용한 다이나믹 프로그래밍", 290);
        vector.put("확률론", 285);
        vector.put("분할 정복을 이용한 거듭제곱", 271);
        vector.put("임의 정밀도 / 큰 수 연산", 249);
        vector.put("오프라인 쿼리", 243);
        vector.put("배낭 문제", 240);
        vector.put("재귀", 224);
        vector.put("값 / 좌표 압축", 213);
        vector.put("런타임 전의 전처리", 198);
        vector.put("최소 스패닝 트리", 196);
        vector.put("에라토스테네스의 체", 195);
        vector.put("이분 매칭", 182);
        vector.put("유클리드 호제법", 182);
        vector.put("방향 비순환 그래프", 179);
        vector.put("볼록 껍질", 172);
        vector.put("선형대수학", 172);
        vector.put("위상 정렬", 168);
        vector.put("플로이드–워셜", 165);
        vector.put("해싱", 162);
        vector.put("최소 공통 조상", 162);
        vector.put("포함 배제의 원리", 150);
        vector.put("강한 연결 요소", 145);
        vector.put("무작위화", 139);
        vector.put("희소 배열", 131);
        vector.put("고속 푸리에 변환", 125);
        vector.put("트라이", 122);
        vector.put("작은 집합에서 큰 집합으로 합치는 테크닉", 122);
        vector.put("덱", 117);
        vector.put("최소 비용 최대 유량", 116);
        vector.put("선분 교차 판정", 110);
        vector.put("제곱근 분할법", 109);
        vector.put("미적분학", 102);
        vector.put("휴리스틱", 100);
        vector.put("모듈로 곱셈 역원", 99);
        vector.put("3차원 기하학", 98);
        vector.put("볼록 껍질을 이용한 최적화", 98);
        vector.put("슬라이딩 윈도우", 97);
        vector.put("접미사 배열과 LCP 배열", 97);
        vector.put("오일러 경로 테크닉", 96);
        vector.put("센트로이드", 95);
        vector.put("스프라그–그런디 정리", 93);
        vector.put("삼분 탐색", 89);
        vector.put("중간에서 만나기", 87);
        vector.put("피타고라스 정리", 85);
        vector.put("가장 긴 증가하는 부분 수열: O(n log n)", 85);
        vector.put("비트 집합", 85);
        vector.put("순열 사이클 분할", 85);
        vector.put("KMP", 81);
        vector.put("Heavy-light 분할", 80);
        vector.put("가우스 소거법", 79);
        vector.put("센트로이드 분할", 76);
        vector.put("최대 유량 최소 컷 정리", 70);
        vector.put("다각형의 넓이", 67);
        vector.put("큐", 63);
        vector.put("오일러 경로", 60);
        vector.put("기댓값의 선형성", 60);
        vector.put("물리학", 60);
        vector.put("페르마의 소정리", 59);
        vector.put("외판원 순회 문제", 58);
        vector.put("2-sat", 57);
        vector.put("단절점과 단절선", 57);
        vector.put("0-1 너비 우선 탐색", 55);
        vector.put("이분 그래프", 48);
        vector.put("이중 연결 요소", 46);
        vector.put("퍼시스턴트 세그먼트 트리", 46);
        vector.put("비둘기집 원리", 42);
        vector.put("연결 리스트", 42);
        vector.put("중국인의 나머지 정리", 42);
        vector.put("선인장", 41);
        vector.put("평면 그래프", 40);
        vector.put("벨만–포드", 39);
        vector.put("스플레이 트리", 37);
        vector.put("볼록 다각형 내부의 점 판정", 36);
        vector.put("오일러 피 함수", 36);
        vector.put("병렬 이분 탐색", 35);
        vector.put("분할 정복을 사용한 최적화", 35);
        vector.put("확장 유클리드 호제법", 34);
        vector.put("mos", 34);
        vector.put("덱을 이용한 구간 최댓값 트릭", 32);
        vector.put("회전하는 캘리퍼스", 29);
        vector.put("다차원 세그먼트 트리", 29);
        vector.put("오일러 지표 (χ=V-E+F)", 29);
        vector.put("정규 표현식", 28);
        vector.put("덱을 이용한 다이나믹 프로그래밍", 28);
        vector.put("아호-코라식", 28);
        vector.put("반평면 교집합", 27);
        vector.put("함수 개형을 이용한 최적화", 26);
        vector.put("벌리캠프–매시", 25);
        vector.put("커넥션 프로파일을 이용한 다이나믹 프로그래밍", 23);
        vector.put("폴라드 로", 23);
        vector.put("매내처", 23);
        vector.put("링크/컷 트리", 22);
        vector.put("트리 동형 사상", 22);
        vector.put("담금질 기법", 22);
        vector.put("머지 소트 트리", 22);
        vector.put("헝가리안", 20);
        vector.put("뫼비우스 반전 공식", 20);
        vector.put("밀러–라빈 소수 판별법", 20);
        vector.put("홀의 결혼 정리", 20);
        vector.put("라빈–카프", 19);
        vector.put("수치해석", 18);
        vector.put("선형 계획법", 18);
        vector.put("플러드 필", 18);
        vector.put("오프라인 동적 연결성 판정", 18);
        vector.put("오목 다각형 내부의 점 판정", 17);
        vector.put("통계학", 17);
        vector.put("함수형 그래프", 17);
        vector.put("생성 함수", 17);
        vector.put("Aliens 트릭", 17);
        vector.put("서큘레이션", 16);
        vector.put("트리 압축", 16);
        vector.put("부분집합의 합 다이나믹 프로그래밍", 15);
        vector.put("쌍대성", 14);
        vector.put("보로노이 다이어그램", 14);
        vector.put("쌍대 그래프", 14);
        vector.put("매트로이드", 13);
        vector.put("뤼카 정리", 13);
        vector.put("키타마사", 12);
        vector.put("트리 분할", 11);
        vector.put("일반적인 매칭", 11);
        vector.put("데카르트 트리", 11);
        vector.put("자릿수를 이용한 다이나믹 프로그래밍", 9);
        vector.put("이산 로그", 9);
        vector.put("최소 외접원", 9);
        vector.put("양방향 탐색", 9);
        vector.put("번사이드 보조정리", 9);
        vector.put("탑 트리", 8);
        vector.put("utf-8 입력 처리", 8);
        vector.put("픽의 정리", 8);
        vector.put("4차원 이상의 기하학", 8);
        vector.put("단조 큐를 이용한 최적화", 8);
        vector.put("z", 8);
        vector.put("크누스 X", 7);
        vector.put("안정 결혼 문제", 7);
        vector.put("델로네 삼각분할", 7);
        vector.put("도미네이터 트리", 7);
        vector.put("회문 트리", 7);
        vector.put("춤추는 링크", 6);
        vector.put("차수열", 6);
        vector.put("로프", 6);
        vector.put("크누스 최적화", 6);
        vector.put("베이즈 정리", 6);
        vector.put("경사 하강법", 5);
        vector.put("히르쉬버그", 5);
        vector.put("현 그래프", 5);
        vector.put("접미사 트리", 5);
        vector.put("이산 제곱근", 5);
        vector.put("다항식 보간법", 5);
        vector.put("차분 공격", 5);
        vector.put("유향 최소 신장 트리", 4);
        vector.put("그린 정리", 4);
        vector.put("스토어–바그너", 4);
        vector.put("린드스트롬–게셀–비엔노 보조정리", 4);
        vector.put("보이어–무어 다수결 투표", 3);
        vector.put("도형에서의 불 연산", 3);
        vector.put("생일 문제", 3);
        vector.put("다중 대입값 계산", 3);
        vector.put("하켄부시 게임", 2);
        vector.put("지수승강 보조정리", 2);
        vector.put("이산 k제곱근", 1);
        vector.put("레드-블랙 트리", 1);
        vector.put("유리 등차수열의 내림 합", 1);

    }

    public static Integer checkAlgorithm(String algorithm) {
        return vector.getOrDefault(algorithm, -1);
    }

    public static Integer overallSum() {
        int sum = 0;
        for (String key : vector.keySet()) {
            sum += vector.get(key);
        }
        return sum;
    }

}
